// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Script, console2} from "forge-std/Script.sol";
import {LoanEngine} from "../src/LoanEngine.sol";
import {ILoanEngine} from "../src/interfaces/ILoanEngine.sol";
import {CreditPolicy} from "../src/CreditPolicy.sol";
import {TranchePool} from "../src/TranchePool.sol";
import {ITranchePool} from "../src/interfaces/ITranchePool.sol";
import {IVerifier} from "../src/interfaces/IVerifier.sol";

/**
 * @title CreateLoanWithProof
 * @notice Creates a loan using a ZK proof generated by the TypeScript script
 *
 * This script expects the proof data to be passed via environment variables
 * or read from a file generated by the proof generator.
 *
 * Usage:
 * 1. First run the TypeScript proof generator to create proof.json
 * 2. Then run this script:
 *
 * forge script script/CreateLoanWithProof.s.sol:CreateLoanWithProof \
 *   --zk-compile --rpc-url http://127.0.0.1:8546 \
 *   --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 \
 *   --broadcast -vvv
 */
contract CreateLoanWithProof is Script {
    function run() external {
        // Get deployed addresses from environment
        address loanEngineAddr = vm.envAddress("LOAN_ENGINE_ADDRESS");
        address creditPolicyAddr = vm.envAddress("CREDIT_POLICY_ADDRESS");
        address tranchePoolAddr = vm.envAddress("TRANCHE_POOL_ADDRESS");

        uint256 deployerPrivateKey = vm.envOr(
            "PRIVATE_KEY",
            uint256(
                0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
            )
        );

        console2.log("=== Create Loan with ZK Proof ===");
        console2.log("LoanEngine:", loanEngineAddr);
        console2.log("CreditPolicy:", creditPolicyAddr);
        console2.log("TranchePool:", tranchePoolAddr);

        LoanEngine loanEngine = LoanEngine(loanEngineAddr);
        CreditPolicy creditPolicy = CreditPolicy(creditPolicyAddr);
        TranchePool tranchePool = TranchePool(tranchePoolAddr);

        vm.startBroadcast(deployerPrivateKey);

        // Step 1: Create and freeze a policy
        console2.log("");
        console2.log("Step 1: Creating and configuring credit policy...");

        uint256 policyVersion = 1;
        creditPolicy.createPolicy(policyVersion);

        // Set scope hash for tier 1
        creditPolicy.setPolicyScopeHash(policyVersion, 1, keccak256("scopeHash_v1_tier1"));

        // Freeze the policy
        creditPolicy.freezePolicy(policyVersion);
        console2.log("  Policy created and frozen");

        // Step 2: Configure TranchePool state
        console2.log("");
        console2.log("Step 2: Configuring TranchePool...");

        // Check current state and advance if needed
        ITranchePool.PoolState currentState = tranchePool.getPoolState();
        console2.log("  Current pool state:", uint256(currentState));

        if (currentState == ITranchePool.PoolState.OPEN) {
            // Need to transition to COMMITTED for loan origination
            console2.log(
                "  Pool in OPEN state - transition to COMMITTED for loan origination"
            );
        }

        vm.stopBroadcast();

        console2.log("");
        console2.log("=== Policy Setup Complete ===");
        console2.log("");
        console2.log("Next steps:");
        console2.log(
            "1. Generate ZK proof using: cd ../zk-scripts && npm run generate-proof"
        );
        console2.log(
            "2. Run CreateLoanWithZkProof script with the generated proof"
        );
    }
}

/**
 * @title CreateLoanWithZkProof
 * @notice Actually creates the loan using proof data from FFI
 */
contract CreateLoanWithZkProof is Script {
    function run() external {
        address loanEngineAddr = vm.envAddress("LOAN_ENGINE_ADDRESS");
        uint256 deployerPrivateKey = vm.envOr(
            "PRIVATE_KEY",
            uint256(
                0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
            )
        );

        LoanEngine loanEngine = LoanEngine(loanEngineAddr);

        console2.log("=== Creating Loan with ZK Proof ===");
        console2.log("LoanEngine:", loanEngineAddr);

        // Run FFI to generate proof
        console2.log("");
        console2.log("Generating ZK proof via FFI...");

        string[] memory inputs = new string[](3);
        inputs[0] = "npx";
        inputs[1] = "tsx";
        inputs[2] = "../zk-scripts/generate_proof_ffi.ts";

        bytes memory result = vm.ffi(inputs);

        // Decode the proof data
        (
            bytes memory proofData,
            bytes32[] memory publicInputs,
            bytes32 policyHash,
            bytes32 loanHash,
            bytes32 nullifierHash,
            bytes32 borrowerCommitment,
            bytes32 underwriterKeyX,
            bytes32 underwriterKeyY,
            bytes32 industryHash,
            uint256 proofTimestamp
        ) = abi.decode(
                result,
                (
                    bytes,
                    bytes32[],
                    bytes32,
                    bytes32,
                    bytes32,
                    bytes32,
                    bytes32,
                    bytes32,
                    bytes32,
                    uint256
                )
            );

        console2.log("  Proof generated successfully");
        console2.log("  Proof size:", proofData.length);
        console2.log("  Public inputs:", publicInputs.length);

        // Verify the proof works
        address verifierAddr = vm.envAddress("VERIFIER_ADDRESS");
        IVerifier verifier = IVerifier(verifierAddr);

        bool isValid = verifier.verify(proofData, publicInputs);
        require(isValid, "Proof verification failed!");
        console2.log("  Proof verified on-chain!");

        vm.startBroadcast(deployerPrivateKey);

        // Create loan params
        ILoanEngine.CreateLoanParams memory params = ILoanEngine
            .CreateLoanParams({
                borrowerCommitment: borrowerCommitment,
                nullifierHash: nullifierHash,
                policyVersion: 1,
                tierId: 1,
                principalIssued: 500_000 * 1e6, // 500k USDC
                aprBps: 1200, // 12%
                originationFeeBps: 100, // 1%
                termDays: 365,
                industry: industryHash,
                underwriterKeyX: underwriterKeyX,
                underwriterKeyY: underwriterKeyY,
                proofTimestamp: proofTimestamp
            });

        // Create the loan
        console2.log("");
        console2.log("Creating loan...");
        loanEngine.createLoan(params, proofData, publicInputs);

        uint256 loanId = loanEngine.getNextLoanId() - 1;
        console2.log("  Loan created with ID:", loanId);

        vm.stopBroadcast();

        console2.log("");
        console2.log("=== SUCCESS ===");
        console2.log("Loan created and verified with ZK proof!");
    }
}
